site_name: Test Site For Publisher for MkDocs
site_url: https://benotdeceived.org/Test-MkDocs-Publisher
site_author: Author's Name
site_description: Testing Publisher for MkDocs 
copyright: >
  &copy; 2024 - Author

# dev_addr: 127.0.0.1:8666

extra_css:
  - assets/stylesheets/publisher.css

extra_javascript:
  # MathJax
  - assets/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Icons hack
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js

watch:
  - overrides

theme:
  name: material
  language: en
  font:
    code: Lato
  custom_dir: overrides
#  logo: publisher_logo.png
#  favicon: publisher_icon.png

  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: Indigo
      accent: blue
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: deep purple
      accent: purple

  features:
    - navigation.tabs
    - navigation.footer  # Prev/Next page
    - navigation.tracking  # Anchor tracking
    - navigation.top  # Back to top
    - navigation.sections  # Useful for an overview
    - navigation.indexes  # Needed for an overview
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      auto_title: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - pub-debugger:
      console_log:
#        show_code_link: true
        enabled: true
#        log_level: DEBUG
#        filter_logger_names:
#          - mkdocs.plugins
#          - mkdocs.structure.files
#          - mkdocs.structure.pages
#          - mkdocs.plugins.publisher.meta.plugin
#          - mkdocs.plugins.publisher.blog.creators
#          - mkdocs.plugins.publisher.blog.modifiers
#          - mkdocs.plugins.publisher.blog.parsers
#          - mkdocs.plugins.publisher.debug.plugin
#          - mkdocs.plugins.publisher.minifier.base
#          - mkdocs.plugins.publisher.minifier.plugin
#          - mkdocs.plugins.publisher.social.plugin
#          - mkdocs.commands.build
  - search
  - pub-meta:
      publish:
        file_default: true
        dir_default: published
  - pub-blog:
      blog_dir: 02-Blog
  - pub-obsidian
  - pub-social
  - pub-minifier